version: '3.2'

services:
  mongo:
    image: 'mongo:4.4.6-bionic'
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
    ports:
      - 27612:27017
    volumes:
      - database-storage:/data/db

  traefik:
    image: "traefik:v2.3"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.useBindPortIP=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.iam.address=:8085"
    ports:
      - "80:80"
      - "8080:8080"
      - "8085:8085"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - server
      - client

  server:
    image: node:14-buster
    user: "${UID}:${GID}"
    working_dir: /home/node/packages/server
    command: "yarn start:dev"
    environment:
      NODE_ENV: development
      DATABASE_URL: "mongodb://${DB_USER}:${DB_PASSWORD}@mongo"
      YARN_VERSION: 1.22.5
      PORT: 9000
      ENVIRONMENT: "development"
      CRYPTO_KEY: H9r5s$$3*BgUZ
      CRYPTO_IV_BASE64: kj4O+MR8Bnm3j+RNcFNCXw==
      JWT_SECRET: 851fFXbwP&68
    volumes:
      - ./packages/data:/home/node/packages/server/src/.data:ro
      - ./:/home/node:rw
      - yarn-dir:/usr/local/share/.config/yarn/global
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`api.galeon.localhost`)"
      - "traefik.http.routers.server.entrypoints=web"
      - 'traefik.http.services.server.loadbalancer.server.port=9000'
    depends_on:
      - mongo

  client:
    image: node:14-buster
    user: "${UID}:${GID}"
    working_dir: /home/node/packages/client
    command: "yarn start"
    environment:
      NODE_ENV: development
      YARN_VERSION: 1.22.5
      ENVIRONMENT: "development"
      API_URL: api.galeon.localhost/api/v1
    volumes:
      - ./packages/data:/home/node/packages/client/src/.data:ro
      - ./:/home/node:rw
      - yarn-dir:/usr/local/share/.config/yarn/global
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`galeon.localhost`)"
      - "traefik.http.routers.client.entrypoints=web"
      - 'traefik.http.services.client.loadbalancer.server.port=4200'
    depends_on:
      - server

volumes:
  database-storage:
  yarn-dir:
